name: Audit Deploy

on:
  push:
    branches:
      - "master"

jobs:
  builds:
    runs-on: ubuntu-lastest

  strategy:
    matrix:
      node-version: [12.x]

  steps:
    - name: Checkout
      uses: actions/Checkout@v1

    - name: Build
      run: npm install
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with: 
        branch: gh-pages
        folder: audit
